// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDetails() {
  return window['go']['main']['App']['AppDetails']();
}

export function AppIcon(arg1) {
  return window['go']['main']['App']['AppIcon'](arg1);
}

export function AppIconSupported() {
  return window['go']['main']['App']['AppIconSupported']();
}

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function CancelAnalyze() {
  return window['go']['main']['App']['CancelAnalyze']();
}

export function CancelDelete() {
  return window['go']['main']['App']['CancelDelete']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CancelUninstall() {
  return window['go']['main']['App']['CancelUninstall']();
}

export function CancelUpdate() {
  return window['go']['main']['App']['CancelUpdate']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function DetectDrives() {
  return window['go']['main']['App']['DetectDrives']();
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function ListPackages() {
  return window['go']['main']['App']['ListPackages']();
}

export function MeasurePaths(arg1) {
  return window['go']['main']['App']['MeasurePaths'](arg1);
}

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function PlanUninstall(arg1) {
  return window['go']['main']['App']['PlanUninstall'](arg1);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function SetAppIcon(arg1) {
  return window['go']['main']['App']['SetAppIcon'](arg1);
}

export function StartAnalyze(arg1) {
  return window['go']['main']['App']['StartAnalyze'](arg1);
}

export function StartDelete(arg1) {
  return window['go']['main']['App']['StartDelete'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}

export function StartUninstall(arg1) {
  return window['go']['main']['App']['StartUninstall'](arg1);
}

export function StartUpdateDownload(arg1, arg2) {
  return window['go']['main']['App']['StartUpdateDownload'](arg1, arg2);
}

export function SystemInfo() {
  return window['go']['main']['App']['SystemInfo']();
}
