// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {updater} from '../models';
import {browser} from '../models';
import {uninstall} from '../models';
import {sysinfo} from '../models';

export function AppDetails():Promise<main.AppInstall>;

export function AppIcon(arg1:string):Promise<string>;

export function AppIconSupported():Promise<boolean>;

export function AppInfo():Promise<Record<string, any>>;

export function CancelAnalyze():Promise<void>;

export function CancelDelete():Promise<void>;

export function CancelScan():Promise<void>;

export function CancelUninstall():Promise<void>;

export function CancelUpdate():Promise<void>;

export function CheckUpdate():Promise<updater.Info>;

export function ClearCache():Promise<main.CacheReport>;

export function DetectDrives():Promise<Array<main.DriveUI>>;

export function InstallUpdate(arg1:string):Promise<void>;

export function ListCategories():Promise<Array<main.CategoryUI>>;

export function ListFolder(arg1:string):Promise<Array<browser.Entry>>;

export function ListPackages():Promise<uninstall.ListResult>;

export function MeasurePaths(arg1:Array<string>):Promise<Array<number>>;

export function OpenLink(arg1:string):Promise<void>;

export function PlanUninstall(arg1:string):Promise<uninstall.Plan>;

export function Reveal(arg1:string):Promise<void>;

export function SetAppIcon(arg1:string):Promise<void>;

export function StartAnalyze(arg1:string):Promise<string>;

export function StartDelete(arg1:main.DeleteRequest):Promise<string>;

export function StartScan(arg1:main.ScanRequest):Promise<string>;

export function StartUninstall(arg1:uninstall.Request):Promise<string>;

export function StartUpdateDownload(arg1:string,arg2:string):Promise<string>;

export function SystemInfo():Promise<sysinfo.Machine>;
