// brandIcons.ts — curated simple-icons imports (official brand SVGs, CC0).
// Importing only what we use keeps the bundle small (~3k icons otherwise).
import {
  siNodedotjs,
  siGo,
  siRust,
  siGradle,
  siApachemaven,
  siCmake,
  siPython,
  siDotnet,
  siXcode,
  siAndroid,
  siOllama,
  siElectron,
  siDocker,
  siHomebrew,
  siPhp,
  siPypi,
  siRubygems,
  siFlutter,
  siTerraform,
  siNuget,
  siJetbrains,
  siVite,
} from "simple-icons";

export const brandIcons: Record<string, { path: string; title: string }> = {
  nodedotjs: siNodedotjs,
  go: siGo,
  rust: siRust,
  gradle: siGradle,
  apachemaven: siApachemaven,
  cmake: siCmake,
  python: siPython,
  dotnet: siDotnet,
  xcode: siXcode,
  android: siAndroid,
  ollama: siOllama,
  electron: siElectron,
  docker: siDocker,
  homebrew: siHomebrew,
  php: siPhp,
  pypi: siPypi,
  rubygems: siRubygems,
  flutter: siFlutter,
  terraform: siTerraform,
  nuget: siNuget,
  jetbrains: siJetbrains,
  vite: siVite,
};
